name: Update rusEFI Reference

on:
  schedule:
    - cron: '30 9 * * *' # update rusEFI reference daily at 5:05 pm
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: rusefi/rusefi/.github/workflows/custom-board-update-rusefi-reference.yaml@master
    permissions:
      contents: write
