name: Update rusEFI Reference

on:
  schedule:
    - cron: '35 15 * * *' # build fresh every 3:35 PM UTC
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: kifir23917/rusefi/.github/workflows/custom-board-update-rusefi-reference.yaml@lts-custom-software-daily-releases
    permissions:
      contents: write
